name: Quarto Build & Deploy
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#no_ci')"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          init-shell: bash
          cache-environment: true
          cache-downloads: true

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto project
        shell: bash -el {0}   # auto-activates the micromamba env for this step
        run: quarto render

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _html   # match this to output-dir in your _quarto.yml (e.g. _book for a book project)
          publish_branch: gh-pages
